version: '3'

services:
  webapi:
    image: webapi/pictures_cloud_runtime:latest
    restart: always
    container_name: webapi
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - database
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - ~/.aspnet/https:/https:ro
  database:
    image: mariadb
    restart: always
    container_name: pictures_cloud_db
    volumes:
      - ./Dumps/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_USER: pictures_cloud_admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: pictures_cloud
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"